#Project Euler Problem 2
#4/13/2012
#Each new term in the Fibonacci sequence is generated by adding the previous
#two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed
#four million, find the sum of the even-valued terms.
#
#

fs = [1,2]
sumfs = fs[1]
i=1

while ((fs[i]+fs[i-1])<=4000000):
    fs.append(fs[i] + fs[i-1])
    if (fs[i+1]%2)==0:
        sumfs = sumfs + fs[i+1]
    i=i+1
print fs
print sumfs

test=0;
for i in fs:
    test=test+i
print test
